### PR TITLE
How to deploy your own IICO to test the front end

### PR DESCRIPTION
**Pull request by stefek99**

### CODE REVIEW

**Comment by epiqueras** [comment]
Check out: https://github.com/kleros/openiico/blob/develop/src/scripts/set-up-sale.js

**Comment by stefek99** [comment]
WOW

I thought the readme is copy-paste auto-generated default...

That script is epic!

1 command as opposed to manually setting everything from scratch...

It's good to know what you do thought - script kitties :)

**Comment by epiqueras** [comment]
I think this unnecessarily long and complex for just saying:

1. Deploy a token and IICO contract. Note that you can use the same token contract with multiple IICO contracts.
2. Use `Token.mint(IICOContractAddress)` to mint tokens for the IICO contract on the token contract.
3. Use `IICO.setToken(tokenContractAddress)` to set the token on the IICO contract.
4. If you are using the IICO contract with whitelist functionality, you'll also need to call `IICO.setWhitelister(whitelisterAddress)` so the whitelister can add addresses to the whitelist.

**Comment by stefek99** [comment]
Another update.

Tutorial landed in a separate place.

Updated readme visible here: https://github.com/stefek99/openiico-contract/tree/run-your-own

Squash my commits:
* https://blog.github.com/2016-04-01-squash-your-commits/
* https://help.github.com/articles/about-pull-request-merges/

**Comment by clesaege** [comment]
Thanks. I merge.

**Pull request merged**
